name: build

on:
  release:
    types: [published]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build on Windows
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r "requirements.txt"

      - name: Build tpp using tppbuild
        run: |
          python "./build.py"


      - name: Uploading asset
        uses: actions/upload-release-asset@v3
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './*.tpp'
          asset_name: 'process_checker_v100_Windows.tpp'
          asset_content_type: 'application/octet-stream'



  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build on Ubuntu
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyinstaller
          pip3 install -r "requirements.txt"

      - name: Build tpp using tppbuild
        run: |
          python3 "./build.py"

      - name: uploading tpp for Ubuntu
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./*.tpp"
          overwrite: true
          file_glob: true


  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build on Ubuntu
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install -r "requirements.txt"

      - name: Build tpp using tppbuild
        run: |
          python3 "./build.py"

      - name: uploading tpp for Ubuntu
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./*.tpp"
          overwrite: true
          file_glob: true
